name: Test packages

on: push

jobs:
  go-hello:
    name: Lint
    runs-on: ubuntu-latest
    env:
      package_name: hello
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.18"

      - name: Setup Taskfile
        uses: Arduino/actions/setup-taskfile@master
        with:
          version: "3.x"

      - name: Lint with golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: ./package/go/${{ env.package_name }}

      - name: Lint
        run: task lint
        working-directory: ./package/go/${{ env.package_name }}

      - name: Test
        run: task test
        working-directory: ./package/go/${{ env.package_name }}
